spring.application.name=businessdomain-identity
server.port = 8081
server.servlet.context-path=/business/v1

# TODO: INVESTIGAR ESTA LINEA
# spring.config.import=optional:configserver:http://localhost:8888

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# Rutas a coincidir
springdoc.paths-to-match=/auth/**,/profile/**,/token/**
# PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# KEYS
# Ubicaciones de las llaves publicas y privadas
jwt.private-key-path=../../infrastructure/keys/private-key.pem
jwt.public-key-path=../../infrastructure/keys/public-key.pem

# SECURITY
logging.level.org.springframework.security=DEBUG