@startuml Workflow
hide methods
skinparam ArrowFontSize 14

' =========================================================
' Datos provenientes indirectamente de PROJECT
' =========================================================

' OWNER representa al usuario administrador del workspace.
'
' boardId hace referencia a un board administrado por
' PROJECT. No es una FK hacia una entidad Board de TASK.
enum Role {
  OWNER
  ADMIN
  MEMBER
  VIEWER
}

entity BoardAccess {
  - id: UUID
  - userId: UUID
  - userActive: boolean
}


'El ID de la entidad Board no es generado automaticamente, se
'toma el ID del Board generado en el microservicio Project, es
'por ello que se coloca <<not generated>>
entity Board {
  - id: UUID <<not generated>>
}


' =========================================================
' Entidades propias de WORKFLOW
' =========================================================

'El valor por defecto del estado es PENDING
enum Status {
  PENDING 
  ON_HOLD
  IN_PROGRESS
  UNDER_REVIEW
  COMPLETED
}

entity Task {
  - id: UUID
  - name: String
  - description: String
  - createdByUserId: UUID
  - createdAt: LocalDateTime
  - updatedAt: LocalDateTime
}

entity Label {
  - id: UUID,
  - content: String
}

enum Color {
  
}

entity Note {
  - id: UUID
  - content: String
  - createdByUserId: UUID
  - createdAt: LocalDateTime
}


' Historial de estados de Task.
' Al crear una Task, se crea también su primer History.

entity History {
  - id: UUID
  - userId: UUID
  - createdAt: LocalDateTime
}


' =========================================================
' Relaciones
' =========================================================
'Una tarea puede tener ninguno, 1 o varios labels diferentes
Task "0..*  " -- "0..*" Label
Task "1" *-- "0..*     " Note
Task " 1" *-- " 1..*" History

Task "0..*" ---> "1 " Status
History " 0..*  " --> " 1  " Status

Board "1   " *-- "1..*    " BoardAccess
Board " 1" *-- "0..*   " Task
BoardAccess "0..*" --> "1  " Role

Board " 1 " *-- "0..*" Label

Label "0..*" --> " 1" Color

@enduml