spring.application.name=businessdomain-project
server.port = 8082
server.servlet.context-path=/business/v1

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5433/project_db?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SECURITY
# Ubicación del archivo de la llave publica
spring.security.oauth2.resourceserver.jwt.public-key-location=file:../../infrastructure/keys/public-key.pem

# URL del dominio del microservicio Identity
# incluye el context path
services.identity.url=http://localhost:8081/business/v1
# URL del dominio del microservicio Workflow
services.workflow.url=http://localhost:8083/business/v1


# Apache HTTP CLIENT
spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.cloud.openfeign.httpclient.enabled=true
